config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'

  #resources :projects do
  resources :texts
    #resources :bands, only: [:new, :create, :edit] do
      #collection do
        #get :search
    #end
  #end
  #end

  #scope shallow_prefix: "sekret" do
    #resources :texts, only: [:edit, :show], shallow: true
  #nd

  resources :texts, only: [:destroy]
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get "/synonymes", to: "synonymes#find_synonyme"
      get "/rimes", to: "synonymes#find_rime"
    end
  end

  end

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>
<div class="banner-content text-center">
  <%= link_to texts_path do  %>
    <h1 class="inspire-title">INSPIRE</h2>
  <% end %>
  <h2 class="inspire-subtitle">Stay cool, you're Inspired...</h2>
  <ul class="mr-auto-new">
    <% if user_signed_in? %>
      <span class=" nav-link-color">Bienvenue <%= current_user.nickname %></span>
      <li class="nav-item dropdown">
      <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "avatar1 dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
      <%= image_tag "https://i1.sndcdn.com/avatars-000478186296-sou2hb-t500x500.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "Mes Textes", texts_path , class: "dropdown-item" %>
      <!--  <%= link_to "Autre action", "#", class: "dropdown-item" %> !-->
      <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
      </li>
    <% else %>
      <li class="nav-item">
      <%= link_to "", new_user_session_path, class: " fas fa-user " %>
      </li>
    <% end %>
  </ul>
</div>
<%# </div> %>
<%= content_for(:footer_class, "footer-home") %>