config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'

  #resources :projects do
  resources :texts
    #resources :bands, only: [:new, :create, :edit] do
      #collection do
        #get :search
    #end
  #end
  #end

  #scope shallow_prefix: "sekret" do
    #resources :texts, only: [:edit, :show], shallow: true
  #nd

  resources :texts, only: [:destroy]
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get "/synonymes", to: "synonymes#find_synonyme"
      get "/rimes", to: "synonymes#find_rime"
    end
  end

  end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy ]

  def index
    @texts = policy_scope(Text)
  end

  def show
  end

  def new
    @text = Text.new
    authorize @text
  end

  def create
    @text = Text.new(text_params)
    @text.user = current_user
    authorize @text

    if @text.save
      redirect_to text_path(@text), notice: 'Le texte a été créé.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @text.update(text_params)
      redirect_to text_path(@text), notice: 'Le texte a été modifié.'
    else
      render :edit
    end
  end

  def destroy
    @text.destroy
    redirect_to texts_path, notice: 'Le texte a été supprimé.'
  end

  def fetchword
  end

  private

  def set_text
    @text = Text.find(params[:id])
    authorize @text
  end

  def text_params
    params.require(:text).permit(:title, :content) # <== le (..., :content) de action text.
  end
end

app/views/texts/_div.html.erb
<div class="box">

<h3>Récap de mes textes</h3>

<ul>
<% @texts.each do |text| %>
      <li><%= text.title %></li>
      <%= link_to 'Voir', sekret_text_path(text) %>
      <%= link_to 'Modifier', edit_sekret_text_path(text) %>
      <!-- %= link_to 'Edit', edit_project_text_path(@project) %> -->
      <%= link_to 'Détruire', text, method: :delete, data: { confirm: 'Êtes-vous sûr-e ?' } %>
<% end %>
</ul>
</div>

app/views/texts/_form.html.erb
<%= content_for(:navbar_class, "project-login") %>

<%= simple_form_for @text do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="text-editor">
    <div class="form-inputs">
      <%= f.input :title, label: "Titre" %>
      <%= f.rich_text_area :content %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Sauvegarder", class: "btn btn-dark" %>
    </div>
  </div>
<% end %>

app/views/texts/edit.html.erb
<div class="banner">
    <h1 class="inspire-title">INSPIRE</h2>
    <h2 class="inspire-subtitle">Stay cool, you're Inspired...</h2>
    <div class="container">
        <div class="sub-container"> 
            <div id="menu">
                <button type="button" class="btn btn-outline-secondary menu-item btn-lg ">synonymes</button>
                <button type="button" class="btn btn-outline-secondary menu-item btn-lg ">rimes</button> 
            </div>
            <div id="open-right-pannel">
                <button type="button" class="btn btn-outline-secondary open-button btn-lg btn-lg btn-block">Open/Close Generator</button>
            </div>
        </div>
        <div class = "action-word " style ="display: none;">
            <input type="text" id ="numbers" class="form-control" placeholder="Nbre de lettres pour la rime" aria-label="Username" aria-describedby="basic-addon1"value="">
        </div>
        <%= render 'form', text: @text %>
    </div>
    <div id="test" class="synonyme" data-action="synonymes"></div>
    <div id="results"></div>
    <span class="close "><i class="far fa-times-circle"></i></span>
    <%=link_to 'Retour', text_path(@text), class: "btn btn-outline-secondary"%>
</div>

app/views/texts/fetchword.html.erb
<h1>Test JS</h1>

<button id="synonyme-btn">Synonyme</button>

app/views/texts/index.html.erb
<%= content_for(:navbar_class, "project-home") %>

<div class="big-container">
    <div class = "project-container">
        <div class="project">
            <% @texts.each do |text| %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url(https://images.unsplash.com/photo-1507838153414-b4b713384a76?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80)">
                    <li>
                    <%= link_to text_path(text), class: "card-title" do %>
                        <%= text.title %></li>
                    <% end %>
                    <div class="icons">
                        <%= link_to text_path(text) do %>
                            <i class="far fa-eye"></i>
                        <% end %>
                        <%= link_to edit_text_path(text) do %>
                            <i class="far fa-edit"></i>
                        <% end %>
                        <%= link_to text_path(text), method: :delete, data: { confirm: 'Êtes-vous sûr-e ?' }, class: "text" do %>
                            <i class="far fa-trash-alt"></i>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <p><%= link_to 'Nouveau texte', new_text_path(@text), class: "text-group" %></p>
        <p><%= link_to 'Retour', texts_path, class: "btn btn-dark" %></p>
    </div>
</div>

app/views/texts/new.html.erb
<div class="banner">
    <h1 class="inspire-title">INSPIRE</h2>
    <h2 class="inspire-subtitle">Stay cool, you're Inspired...</h2>
    <div class="container">
        <div class="sub-container"> 
            <div id="menu">
                <button type="button" class="btn btn-outline-secondary menu-item btn-lg ">synonymes</button>
                <button type="button" class="btn btn-outline-secondary menu-item btn-lg ">rimes</button> 
            </div>
            <div id="open-right-pannel">
                <button type="button" class="btn btn-outline-secondary open-button btn-lg btn-lg btn-block">Open/Close Generator</button>
            </div>
        </div>
        <div class = "action-word " style ="display: none;">
            <input type="text" id ="numbers" class="form-control" placeholder="Nbre de lettres pour la rime" aria-label="Username" aria-describedby="basic-addon1"value="">
        </div>
        <%= render 'form', text: @text %>
    </div>
    <div id="test" class="synonyme" data-action="synonymes"></div>
    <div id="results"></div>
    <span class="close "><i class="far fa-times-circle"></i></span>
    <%# <div id="out-click"></div> %>
    <%#= link_to 'Retour', project_path(@project), class: "btn btn-outline-secondary" %>
</div>

app/views/texts/show.html.erb
<%= content_for(:navbar_class, "project-home") %>
<div class="big-container">
      <div class="bgtext"></div>
      <div class = "project-container">
            <div class="pr-content">
                  <h1 class=text-center><%= @text.title %></h1>
                  <p><%= @text.content %></p>
                  <p><%= link_to 'Retour', texts_path, class: "btn-text" %></p>
            </div>
      </div>
</div>